const $=s=>document.querySelector(s);const home=$('#home'),train=$('#train'),modal=$('#modal'),history=$('#history'),toast=$('#toast');
const techniques=[
{id:'chudan',name:'Chudan Tsuki',jp:'中段突き',sub:'Mid-level Punch',art:'chudan.png',count:+localStorage.getItem('ichiman_chudan')||0,live:true},
{id:'jodan',name:'Jodan Tsuki',jp:'上段突き',sub:'Head-level Punch',art:'jodan.png',count:+localStorage.getItem('ichiman_jodan')||0,live:true},
{id:'shita',name:'Shita Tsuki',jp:'下突き',sub:'Short Punch',art:'chudan.png',count:+localStorage.getItem('ichiman_shita')||0,live:true},
{id:'hijiate',name:'Hijiate',jp:'肘当て',sub:'Rising Elbow Strike',art:'jodan.png',count:+localStorage.getItem('ichiman_hijiate')||0,live:true},
{id:'mawashi-empi',name:'Mawashi Empi',jp:'回し肘',sub:'Round Elbow Strike',art:'chudan.png',count:+localStorage.getItem('ichiman_mawashi_empi')||0,live:true},
{id:'ura-uchi',name:'Ura Uchi',jp:'裏打ち',sub:'Forward Back Fist',art:'chudan.png',count:+localStorage.getItem('ichiman_ura_uchi')||0,live:true},
{id:'yoko-ura',name:'Yoko Ura Uchi',jp:'横裏打ち',sub:'Side Back Fist',art:'chudan.png',count:+localStorage.getItem('ichiman_yoko_ura')||0,live:true}
];
let current=techniques[0],last=null;let logs=JSON.parse(localStorage.getItem('ichiman_logs')||'{}');
function save(t){localStorage.setItem('ichiman_'+t.id.replaceAll('-','_'),t.count);localStorage.setItem('ichiman_logs',JSON.stringify(logs))}
function row(t){let p=Math.min(1,t.count/10000),hs=[0,.25,.5,.75].map(v=>`<span class="stalk"><i style="height:${Math.max(0,Math.min(1,(p-v)*4))*100}%"></i></span>`).join('');return `<article class="tech" data-id="${t.id}"><img class="art" src="assets/${t.art}"><div><h3>${t.name}</h3><div class="jp">${t.jp} · ${t.sub}</div><span class="count ${t.count>=10000?'done':''}">${t.count.toLocaleString()} / 10,000 ${t.count>=10000?'✓':''}</span>${t.count<10000?`<div class="controls"><button data-add="10">+10</button><button data-add="100">+100</button><button class="custom">+</button></div>`:`<div class="complete">COMPLETED FOR LIFE</div>`}</div><div><div class="bamboo">${hs}</div></div></article>`}
function render(){ $('#list').innerHTML=techniques.map(row).join(''); document.querySelectorAll('.tech').forEach(el=>{let t=techniques.find(x=>x.id===el.dataset.id);el.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(t,+b.dataset.add));let c=el.querySelector('.custom');if(c)c.onclick=()=>{current=t;$('.modalTech').innerHTML=`${t.name}<small>${t.sub}</small>`;modal.classList.remove('hidden')};el.querySelector('.count').onpointerdown=()=>{window.lp=setTimeout(()=>showHistory(t),550)};el.querySelector('.count').onpointerup=()=>clearTimeout(window.lp);el.querySelector('.count').onpointerleave=()=>clearTimeout(window.lp)})}
function add(t,n){let before=t.count;t.count=Math.min(10000,t.count+n);let actual=t.count-before;if(!actual)return;last={t,n:actual};logs[t.id]=logs[t.id]||[];logs[t.id].unshift({n:actual,at:new Date().toISOString()});save(t);render();let art=document.querySelector(`[data-id="${t.id}"] .art`);art?.classList.add('punch');setTimeout(()=>art?.classList.remove('punch'),180);$('#toastText').textContent=`+${actual} · ${t.name}`;toast.classList.remove('hidden');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.add('hidden'),3500)}
function showHistory(t){current=t;$('#history h2').textContent=t.name;let arr=logs[t.id]||[];$('#historyRows').innerHTML=arr.length?arr.slice(0,8).map(x=>`<div class="historyRow"><span>${new Date(x.at).toLocaleDateString()}</span><b>+${x.n}</b></div>`).join(''):'<div class="historyRow"><span>No additions yet</span></div>';history.classList.remove('hidden')}
$('#enter').onclick=()=>{home.classList.add('hidden');train.classList.remove('hidden')};$('#homeBtn').onclick=()=>{train.classList.add('hidden');home.classList.remove('hidden')};$('#close').onclick=()=>modal.classList.add('hidden');$('.presets').querySelectorAll('button').forEach(b=>b.onclick=()=>$('#num').value=b.textContent);$('#addCustom').onclick=()=>{let n=parseInt($('#num').value);if(n>0)add(current,n);modal.classList.add('hidden')};$('#undo').onclick=()=>{if(!last)return;last.t.count-=last.n;(logs[last.t.id]||[]).shift();save(last.t);last=null;render();toast.classList.add('hidden')};$('#historyClose').onclick=()=>history.classList.add('hidden');$('#editTotal').onclick=()=>{let v=prompt('Set total reps for '+current.name,current.count);if(v!==null&&!isNaN(v)){current.count=Math.max(0,Math.min(10000,+v));save(current);render();history.classList.add('hidden')}};render();
