const T=window.TECHNIQUES, belts=[['white','WHITE BELT',0],['yellow','YELLOW BELT',1],['orange','ORANGE BELT',2],['green','GREEN BELT',3],['blue','BLUE BELT',4],['red','RED BELT',5],['brown','BROWN BELT',6],['black','BLACK BELT',7]];
let S=JSON.parse(localStorage.getItem('ichimanState')||'null')||{belt:'white',cat:'strikes',actual:'white',reps:{},history:{},activated:{}};
const save=()=>localStorage.setItem('ichimanState',JSON.stringify(S)), q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
function screen(id){qa('.screen').forEach(x=>x.classList.remove('active'));q('#'+id).classList.add('active');closeDrawer();if(id==='training')render();if(id==='grove')renderGrove()}
// Training is the default. Splash is only a brief entrance on a fresh browser session.
if(!sessionStorage.getItem('ichimanEntered')){sessionStorage.setItem('ichimanEntered','1');screen('splash');setTimeout(()=>screen('training'),800)}else render();
qa('[data-training]').forEach(b=>b.onclick=()=>screen('training'));qa('[data-dojo]').forEach(b=>b.onclick=()=>screen('home'));
qa('[data-menu]').forEach(b=>b.onclick=()=>{q('#drawer').classList.add('open');q('#veil').classList.add('open')});qa('[data-close]').forEach(b=>b.onclick=closeDrawer);function closeDrawer(){q('#drawer').classList.remove('open');q('#veil').classList.remove('open')}qa('[data-go]').forEach(b=>b.onclick=()=>screen(b.dataset.go));qa('[data-cat]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;save();render()});
function stage(n){return Math.min(4,Math.floor((n||0)/2500))}function listForBelt(){return T.filter(t=>t.belt===S.belt&&t.category===S.cat)}
function render(){q('#beltTitle').textContent=(belts.find(b=>b[0]===S.belt)||belts[0])[1];qa('[data-cat]').forEach(b=>b.classList.toggle('on',b.dataset.cat===S.cat));const list=listForBelt();q('#categoryBamboo').innerHTML=list.map(t=>`<img src="assets/bamboo${stage(S.reps[t.id]||0)}.png" title="${t.name}">`).join('');q('#techList').innerHTML=list.length?list.map(t=>row(t)).join(''):`<div class="empty"><b>No new ${S.cat}.</b><span>Earlier techniques keep the same lifetime counters.</span></div>`;q('#beltRack').innerHTML=belts.map(b=>`<button class="${S.belt===b[0]?'on':''}" data-belt="${b[0]}" aria-label="${b[1]}"><img src="assets/belt${b[2]}.jpg"></button>`).join('');qa('[data-belt]').forEach(b=>b.onclick=()=>{S.belt=b.dataset.belt;save();render()});qa('.add').forEach(b=>b.onclick=()=>add(b.dataset.id,+b.dataset.n,b.closest('.tech')));qa('.custom').forEach(b=>b.onclick=()=>custom(b.dataset.id));qa('.count').forEach(b=>{let timer;b.onpointerdown=()=>timer=setTimeout(()=>historyModal(b.dataset.id),550);b.onpointerup=b.onpointerleave=()=>clearTimeout(timer)});qa('.activate').forEach(b=>b.onclick=()=>{S.activated[b.dataset.id]=true;save();render()})}
function row(t){let n=S.reps[t.id]||0,done=n>=10000,locked=t.needsCheck&&!S.activated[t.id];return `<article class="tech ${done?'complete':''}" data-tech="${t.id}"><img class="art" src="${t.art}"><div class="tech-info"><div class="tech-name"><h2>${t.name}</h2><span>${t.english}</span></div><button class="count" data-id="${t.id}">${n.toLocaleString()} / 10,000 ${done?'✓':''}</button>${locked?`<button class="activate" data-id="${t.id}">ACTIVATE AFTER INSTRUCTOR CHECK</button>`:`<div class="actions"><button class="add" data-id="${t.id}" data-n="10">+10</button><button class="add" data-id="${t.id}" data-n="100">+100</button><button class="custom" data-id="${t.id}">+</button>${t.video?`<button onclick="window.open('${t.video}','_blank')">▶</button>`:''}</div>`}</div></article>`}
function add(id,n,el){let old=S.reps[id]||0,now=Math.min(10000,old+n);S.reps[id]=now;(S.history[id]??=[]).unshift({n:now-old,at:new Date().toISOString()});save();if(el){el.classList.remove('punch');void el.offsetWidth;el.classList.add('punch')}toast(`+${now-old} · ${now.toLocaleString()} / 10,000`,()=>{S.reps[id]=old;S.history[id]?.shift();save();render()});setTimeout(render,260)}
function custom(id){openModal(`<h2>ADD REPS</h2><h3>${T.find(t=>t.id===id).name}</h3><input id="repInput" class="biginput" type="number" inputmode="numeric" value="50" min="1" max="10000"><div class="presets">${[10,25,50,100].map(n=>`<button data-preset="${n}">${n}</button>`).join('')}</div><button class="addbtn" id="confirmAdd">ADD</button>`);qa('[data-preset]').forEach(b=>b.onclick=()=>q('#repInput').value=b.dataset.preset);q('#confirmAdd').onclick=()=>{let n=Math.max(1,+q('#repInput').value||0);closeModal();add(id,n)}}
function historyModal(id){let t=T.find(x=>x.id===id),h=S.history[id]||[];openModal(`<h2>${t.name}</h2><p>${(S.reps[id]||0).toLocaleString()} / 10,000</p><div class="history">${h.slice(0,12).map(x=>`<div class="history-row"><span>${new Date(x.at).toLocaleString()}</span><b>+${x.n}</b></div>`).join('')||'<p>No additions yet.</p>'}<button id="editTotal">EDIT TOTAL</button></div>`);q('#editTotal').onclick=()=>{let v=prompt('Set total reps (0–10,000)',S.reps[id]||0);if(v!==null){S.reps[id]=Math.max(0,Math.min(10000,+v||0));save();closeModal();render()}}}
function openModal(html){q('#modalBody').innerHTML=html;q('#modal').classList.add('open')}function closeModal(){q('#modal').classList.remove('open')}qa('[data-modal-close]').forEach(b=>b.onclick=closeModal);q('#modal').onclick=e=>{if(e.target===q('#modal'))closeModal()};function toast(txt,undo){let t=q('#toast');t.innerHTML=txt+' &nbsp; <u>UNDO</u>';t.classList.add('show');let active=true;t.onclick=()=>{if(active){undo();active=false;t.classList.remove('show')}};setTimeout(()=>{active=false;t.classList.remove('show')},3500)}
function renderGrove(){let completed=T.filter(t=>(S.reps[t.id]||0)>=10000), growing=T.filter(t=>(S.reps[t.id]||0)>0&&(S.reps[t.id]||0)<10000);q('#groveVisual').innerHTML=`<div class="grove-scene"><div class="grove-bamboo">${[...completed,...growing].map(t=>`<button title="${t.name}" data-grove="${t.id}"><img src="assets/bamboo${stage(S.reps[t.id]||0)}.png"></button>`).join('')||'<div class="grove-empty">Your first bamboo shoot appears when you begin practising.</div>'}</div><div class="grove-stone">${completed.length} MATURE · ${growing.length} GROWING</div></div>`;qa('[data-grove]').forEach(b=>b.onclick=()=>{let t=T.find(x=>x.id===b.dataset.grove),n=S.reps[t.id]||0;openModal(`<h2>${t.name}</h2><p>${t.english}</p><p class="grove-count">${n.toLocaleString()} / 10,000 ${n>=10000?'✓':''}</p>`)})}
q('#actualGrade').innerHTML=belts.map(b=>`<option value="${b[0]}" ${S.actual===b[0]?'selected':''}>${b[1]}</option>`).join('');q('#actualGrade').onchange=e=>{S.actual=e.target.value;save()};q('#export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='ichiman-backup.json';a.click()};q('#import').onchange=e=>{let r=new FileReader();r.onload=()=>{try{S=JSON.parse(r.result);save();alert('Backup imported.')}catch{alert('Invalid backup file.')}};r.readAsText(e.target.files[0])};q('#reset').onclick=()=>{if(confirm('Reset every ICHIMAN counter and history?')){localStorage.removeItem('ichimanState');location.reload()}};
